In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("airbnb.csv")
df.head()

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...",...,5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...",...,11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12805 entries, 0 to 12804
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    12805 non-null  int64
 1   id            12805 non-null  int64
 2   name          12805 non-null  object
 3   rating        12805 non-null  object
 4   reviews       12805 non-null  object
 5   host_name     12797 non-null  object
 6   host_id       12805 non-null  float64
 7   address       12805 non-null  object
 8   features      12805 non-null  object
 9   amenities     12805 non-null  object
 10  safety_rules  12805 non-null  object
 11  hourse_rules  12805 non-null  object
 12  img_links     12805 non-null  object
 13  price         12805 non-null  int64
 14  country       12805 non-null  object
 15  bathrooms     12805 non-null  int64
 16  beds          12805 non-null  int64
 17  guests        12805 non-null  int64
 18  toiles        12805 non-null  int64
 19  bedrooms      12805 non-null  int64
 20  studios       12805 non-null  int64
 21  checkin       12005 non-null  object
 22  checkout      10355 non-null  object
dtypes: float64(1), int64(9), object(13)
memory usage: 2.2+ MB

In [4]:
df.shape

(12805, 23)

In [5]:
df.describe()

,Unnamed: 0,id,host_id,price,bathrooms,beds,guests,toiles,bedrooms,studios
count,12805.000000,1.280500e+04,1.280500e+04,1.280500e+04,12805.000000,12805.000000,12805.000000,12805.000000,12805.000000,12805.000000
mean,6402.000000,7.525187e+16,1.638192e+08,1.769780e+04,1.874424,3.316751,5.213745,0.019211,2.136041,0.023585
std,3696.629433,2.007933e+17,1.413622e+08,4.569364e+04,2.091399,4.037791,3.808830,0.137272,2.359005,0.151757
min,0.000000,1.313100e+04,2.303900e+04,3.930000e+02,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,3201.000000,2.023958e+07,3.700032e+07,3.994000e+03,1.000000,1.000000,2.000000,0.000000,1.000000,0.000000
50%,6402.000000,3.682229e+07,1.256459e+08,8.175000e+03,1.000000,2.000000,4.000000,0.000000,1.000000,0.000000
75%,9603.000000,4.999760e+07,2.639623e+08,1.606200e+04,2.000000,4.000000,6.000000,0.000000,3.000000,0.000000
max,12804.000000,7.017905e+17,4.758973e+08,1.907963e+06,50.000000,98.000000,16.000000,1.000000,50.000000,1.000000

In [6]:
df.apply(lambda x : len(x.unique()))

Unnamed: 0      12805
id              12805
name            12716
rating             77
reviews           409
host_name        6838
host_id         10375
address          6287
features         2548
amenities       11630
safety_rules      257
hourse_rules     5800
img_links       12711
price            7460
country           148
bathrooms          29
beds               49
guests             16
toiles              2
bedrooms           32
studios             2
checkin           154
checkout           22
dtype: int64

In [7]:
df["amenities"]

0        Mountain view,Valley view,Lake access,Kitchen,...
1        Kitchen,Wifi,Dedicated workspace,Free parking ...
2        Mountain view,Kitchen,Wifi,Dedicated workspace...
3        Mountain view,Valley view,Kitchen,Wifi,Free pa...
4        Kitchen,Wifi,Free parking on premises,TV,Air c...
                               ...
12800    Kitchen,Wifi,Free parking on premises,Private ...
12801    Wifi,Free on-street parking,Air conditioning,G...
12802    Wifi,Breakfast,Long-term stays allowed,Unavail...
12803    Kitchen,Wifi,Dedicated workspace,Free parking ...
12804    Sea view,Beach access – Beachfront,Kitchen,Wif...
Name: amenities, Length: 12805, dtype: object

In [8]:
df["checkout"].unique()

array([' 12 00 pm', ' 10 00 am', ' 11 00 am', nan, ' 3 00 pm', ' 1 00 pm',
       ' 12 00 am', ' 6 00 pm', ' 4 00 pm', ' 5 00 pm', ' 9 00 am',
       ' 2 00 pm', ' 8 00 am', ' 7 00 am', ' 1 00 am', ' 2 00 am',
       ' 11 00 pm', ' 10 00 pm', ' 3 00 am', ' 8 00 pm', ' 7 00 pm',
       ' 4 00 am'], dtype=object)

In [9]:
df.isnull().sum()

Unnamed: 0         0
id                 0
name               0
rating             0
reviews            0
host_name          8
host_id            0
address            0
features           0
amenities          0
safety_rules       0
hourse_rules       0
img_links          0
price              0
country            0
bathrooms          0
beds               0
guests             0
toiles             0
bedrooms           0
studios            0
checkin          800
checkout        2450
dtype: int64

In [83]:
# host_name , checkin , checkout have null values .

In [10]:
df.drop(df.columns[[0, 1 , 2]], axis=1, inplace=True)

In [11]:
df[df['rating'] == 'New']

,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
1,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
4,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/73973308-e...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm
5,New,0,Casamia,261290482.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,2 beds,1 bathroom","Lake view,Mountain view,Waterfront,Wifi,Dedica...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/miso/Hosti...,14729,Turkey,1,2,2,0,1,0,After 2 00 pm,12 00 pm
6,New,0,Stephen,15084529.0,"Kaş, Antalya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Garden view,Mountain view,Kitchen,Wifi,Dedicat...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 3:00 pm,Check out: 11:00 am,No...",https://a0.muscache.com/im/pictures/prohost-ap...,12312,Turkey,1,1,2,0,1,0,After 3 00 pm,11 00 am
7,New,0,Caner,318794897.0,"Akçalı, Giresun, Turkey","8 guests,1 bedroom,2 beds,1 bathroom","Wifi,Dedicated workspace,Free parking on premi...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: Flexible,Self check-in with building...",https://a0.muscache.com/im/pictures/97046585-1...,13655,Turkey,1,2,8,0,1,0,Flexible,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12790,New,1,Onda,331826286.0,"Nam-myeon, Jeongseon-gun, Gangwon Province, So...","5 guests,1 bedroom,1 bathroom","Waterfront,Kitchen,Wifi,Free parking on premis...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 10:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/prohost-ap...,4980,South Korea,1,0,5,0,1,0,3 00 pm - 10 00 pm,11 00 am
12791,New,1,Pt. Archi,110392424.0,"Kecamatan Kuta Selatan, Bali, Indonesia","2 guests,1 bedroom,1 bed,1 bathroom","Wifi,Free parking on premises,Private pool,Pet...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Self check-in with loc...",https://a0.muscache.com/im/pictures/641046c0-e...,10729,Indonesia,1,1,2,0,1,0,After 2 00 pm,NaN
12793,New,0,Black Lava Camp,454606239.0,"Kintamani, Bali, Indonesia","2 guests,1 bedroom,1 bed,Shared toilet with sink","Free parking on premises,Pool,Fire pit,Long-te...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",Check-in: After 3:00 pm,https://a0.muscache.com/im/pictures/miso/Hosti...,3428,Indonesia,0,1,2,1,1,0,After 3 00 pm,NaN
12795,New,0,Maria,122986750.0,"Augusta, Sicilia, Italy","5 guests,1 bedroom,2 beds,1.5 bathrooms","Beach access – Beachfront,Kitchen,Wifi,Dedicat...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 1:00 pm - 8:00 pm,Check out: 11:00 a...",https://a0.muscache.com/im/pictures/8cac9ffa-5...,8841,Italy,1,2,5,0,1,0,1 00 pm - 8 00 pm,11 00 am
12799,New,0,Daphne Belvilla,385223440.0,"Syracuse, Sicilia, Italy","8 guests,4 bedrooms,4 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free on-stree...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 2:00 pm - 8:00 pm,Check out: 10:00 a...",https://a0.muscache.com/im/pictures/prohost-ap...,20311,Italy,2,4,8,0,4,0,2 00 pm - 8 00 pm,10 00 am

In [12]:
df.drop('host_id' , axis=1, inplace=True)
df.drop('host_name' , axis=1, inplace=True)
df.drop('address' , axis=1, inplace=True)
df.drop('features' , axis=1, inplace=True)
df.drop('img_links' , axis=1, inplace=True)
df.drop('safety_rules' , axis=1, inplace=True)

In [13]:
df

,rating,reviews,amenities,hourse_rules,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,4.71,64,"Mountain view,Valley view,Lake access,Kitchen,...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,New,0,"Kitchen,Wifi,Dedicated workspace,Free parking ...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,4.85,68,"Mountain view,Kitchen,Wifi,Dedicated workspace...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,5.0,13,"Mountain view,Valley view,Kitchen,Wifi,Free pa...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,New,0,"Kitchen,Wifi,Free parking on premises,TV,Air c...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12800,4.94,16,"Kitchen,Wifi,Free parking on premises,Private ...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",4288,South Korea,8,0,4,0,0,0,3 00 pm - 11 00 pm,11 00 am
12801,4.67,6,"Wifi,Free on-street parking,Air conditioning,G...","Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...",15200,Indonesia,0,1,2,1,1,0,3 00 pm - 10 00 pm,12 00 pm
12802,4.67,3,"Wifi,Breakfast,Long-term stays allowed,Unavail...",Check-in: After 3:00 pm,9103,Uganda,1,2,2,0,1,0,After 3 00 pm,NaN
12803,4.86,7,"Kitchen,Wifi,Dedicated workspace,Free parking ...","Check-in: Flexible,Check out: 12:00 pm,No pets...",42262,Indonesia,2,4,8,0,2,0,Flexible,12 00 pm
12804,4.85,13,"Sea view,Beach access – Beachfront,Kitchen,Wif...","Check-in: After 4:00 pm,Check out: 11:00 am,Se...",9909,Japan,1,2,5,0,1,0,After 4 00 pm,11 00 am

In [15]:
def clean_rating(rating_str):
    try:
        return float(rating_str)
    except ValueError:
        return None
df['rating'] = df['rating'].apply(clean_rating)

mean_ratings = df[df['rating'].notna()].groupby('country')['rating'].mean()

for country in mean_ratings.index:
    new_rating_mask = (df['rating'].isnull()) & (df['country'] == country)
    df.loc[new_rating_mask, 'rating'] = mean_ratings[country]

In [16]:
df['rating'].unique()

array([4.71      , 4.82440594, 4.85      , 5.        , 4.84226415,
       4.67      , 4.97      , 4.89      , 4.83      , 4.87      ,
       4.9       , 4.75      , 4.76      , 4.84      , 4.79      ,
       4.82      , 4.93      , 4.96      , 4.6       , 4.64      ,
       4.82360656, 4.68      , 4.8       , 4.83660131, 4.69      ,
       4.85414239, 4.925     , 4.58      , 4.63      , 4.86214575,
       4.91      , 4.655     , 4.88      , 4.94      , 4.92      ,
       4.84693333, 4.86      , 4.911875  , 4.78      , 4.83793269,
       4.57      , 4.99      , 4.98      , 4.89479592, 4.74      ,
       4.91350649, 4.88583333, 4.90863636, 4.7       , 4.77      ,
       4.72      , 4.87973214, 4.92      , 4.73      , 4.84333333,
       4.83857143, 4.95      , 4.87258065, 4.89837838, 4.81      ,
       4.84265487, 4.53      , 4.59      , 4.62      , 4.88266304,
       4.61      ,        nan, 4.51      , 4.54      , 4.56      ,
       4.65      , 4.89233333, 4.87279412, 4.87854396, 4.82965812,
       4.93702703, 4.84661017, 4.83066667, 4.55      , 4.66      ,
       4.52      , 4.5       , 4.83653465, 4.815     , 4.82677966,
       4.88736842, 4.83756098, 4.8715508 , 4.82058824, 4.84227273,
       4.8175    , 4.884     , 4.82363636, 4.75571429, 4.89612903,
       4.92230769, 4.81      , 4.91194805, 4.8356    , 4.959375  ,
       4.8775    , 4.33      , 4.26      , 3.33      , 4.2       ,
       4.        , 4.48      , 4.38      , 3.        , 4.8692    ,
       4.8451875 , 4.86666667, 4.85342105, 4.9125    , 4.888     ,
       4.49      , 4.28      , 4.81222222, 4.90166667, 4.93428571,
       4.85170213, 4.81702703, 4.45      , 4.91375   , 4.25      ,
       4.89285714, 4.8475    , 4.91534091, 4.92580645, 4.91      ,
       4.782     , 4.86307692, 4.36      , 4.46      , 4.44      ,
       4.43      , 3.75      , 3.25      , 4.13      , 4.15      ,
       3.88      , 4.29      , 4.4       , 3.5       , 4.84467005,
       4.31      , 4.87789474])

In [17]:
import re
def extract_hour_convert_to_24hr(time_str):
    if isinstance(time_str, str) and time_str.strip().lower() == 'flexible':
        return 'Flexible'    
    if isinstance(time_str, str):
        match = re.search(r'(\d{1,2})', time_str)
        if match:
            hour = int(match.group(1))
            if hour < 12 and 'pm' in time_str.lower():
                hour += 12
            return f'{hour:02}:00'    
    if isinstance(time_str, str):
        try:
            hour = int(time_str)
            return f'{hour:02}:00'
        except ValueError:
            pass
    return None
df['checkin_num'] = df['checkin'].apply(extract_hour_convert_to_24hr)

In [18]:
def convert_to_numeric(time_str):
    time_mapping = {
        '01:00': 1,
        '06:00': 6,
        '08:00': 8,
        '09:00': 9,
        '10:00': 10,
        '11:00': 11,
        '12:00': 12,
        '13:00': 13,
        '14:00': 14,
        '15:00': 15,
        '16:00': 16,
        '17:00': 17,
        '18:00': 18,
        '19:00': 19,
        '20:00': 20,
        '21:00': 21,
        '22:00': 22,
        '23:00': 23,
        'Flexible': 'Flexible' 
    }
    
    return time_mapping.get(time_str, None)

df['checkin_final'] = df['checkin_num'].apply(convert_to_numeric)

In [20]:
df['checkin_final'].value_counts()

checkin_final
15          4093
14          2607
16          1363
12          1109
Flexible     926
13           897
17           268
11           144
23           133
22           118
10            86
20            64
18            57
8             50
21            42
9             31
19            13
1              3
6              1
Name: count, dtype: int64

In [21]:
def extract_hour(time_str):
    try:
        parts = str(time_str).split()
        hour = int(parts[0])
        period = parts[2].lower()    
        if period == 'pm' and hour != 12:
            hour += 12
        elif period == 'am' and hour == 12:
            hour = 0
        
        return hour
    except (IndexError, ValueError):
        return None  
df['checkout_final'] = df['checkout'].apply(extract_hour)

In [26]:
df['checkout_final'].value_counts()

checkout_final
11.0    4391
12.0    2648
10.0    2622
9.0      186
13.0     178
0.0       82
14.0      72
15.0      50
8.0       30
16.0      18
17.0      16
18.0      15
23.0      15
1.0       12
2.0        6
22.0       4
7.0        3
3.0        3
20.0       2
19.0       1
4.0        1
Name: count, dtype: int64

In [27]:
df

,rating,reviews,amenities,hourse_rules,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout,checkin_num,checkin_final,checkout_final
0,4.710000,64,"Mountain view,Valley view,Lake access,Kitchen,...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm,Flexible,Flexible,12.0
1,4.824406,0,"Kitchen,Wifi,Dedicated workspace,Free parking ...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am,16:00,16,10.0
2,4.850000,68,"Mountain view,Kitchen,Wifi,Dedicated workspace...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm,13:00,13,12.0
3,5.000000,13,"Mountain view,Valley view,Kitchen,Wifi,Free pa...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm,14:00,14,12.0
4,4.824406,0,"Kitchen,Wifi,Free parking on premises,TV,Air c...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm,14:00,14,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12800,4.940000,16,"Kitchen,Wifi,Free parking on premises,Private ...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",4288,South Korea,8,0,4,0,0,0,3 00 pm - 11 00 pm,11 00 am,15:00,15,11.0
12801,4.670000,6,"Wifi,Free on-street parking,Air conditioning,G...","Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...",15200,Indonesia,0,1,2,1,1,0,3 00 pm - 10 00 pm,12 00 pm,15:00,15,12.0
12802,4.670000,3,"Wifi,Breakfast,Long-term stays allowed,Unavail...",Check-in: After 3:00 pm,9103,Uganda,1,2,2,0,1,0,After 3 00 pm,NaN,15:00,15,NaN
12803,4.860000,7,"Kitchen,Wifi,Dedicated workspace,Free parking ...","Check-in: Flexible,Check out: 12:00 pm,No pets...",42262,Indonesia,2,4,8,0,2,0,Flexible,12 00 pm,Flexible,Flexible,12.0
12804,4.850000,13,"Sea view,Beach access – Beachfront,Kitchen,Wif...","Check-in: After 4:00 pm,Check out: 11:00 am,Se...",9909,Japan,1,2,5,0,1,0,After 4 00 pm,11 00 am,16:00,16,11.0

In [28]:
df.drop('checkin' , axis=1, inplace=True)
df.drop('checkin_num' , axis=1, inplace=True)
df.drop('checkout' , axis=1, inplace=True)

In [29]:
df

,rating,reviews,amenities,hourse_rules,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin_final,checkout_final
0,4.710000,64,"Mountain view,Valley view,Lake access,Kitchen,...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",8078,Turkey,1,1,2,0,2,0,Flexible,12.0
1,4.824406,0,"Kitchen,Wifi,Dedicated workspace,Free parking ...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",4665,Turkey,2,2,4,0,2,0,16,10.0
2,4.850000,68,"Mountain view,Kitchen,Wifi,Dedicated workspace...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",5991,Georgia,1,3,4,0,1,0,13,12.0
3,5.000000,13,"Mountain view,Valley view,Kitchen,Wifi,Free pa...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",11339,Turkey,1,2,4,0,1,0,14,12.0
4,4.824406,0,"Kitchen,Wifi,Free parking on premises,TV,Air c...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",6673,Turkey,1,1,2,0,1,0,14,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12800,4.940000,16,"Kitchen,Wifi,Free parking on premises,Private ...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",4288,South Korea,8,0,4,0,0,0,15,11.0
12801,4.670000,6,"Wifi,Free on-street parking,Air conditioning,G...","Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...",15200,Indonesia,0,1,2,1,1,0,15,12.0
12802,4.670000,3,"Wifi,Breakfast,Long-term stays allowed,Unavail...",Check-in: After 3:00 pm,9103,Uganda,1,2,2,0,1,0,15,NaN
12803,4.860000,7,"Kitchen,Wifi,Dedicated workspace,Free parking ...","Check-in: Flexible,Check out: 12:00 pm,No pets...",42262,Indonesia,2,4,8,0,2,0,Flexible,12.0
12804,4.850000,13,"Sea view,Beach access – Beachfront,Kitchen,Wif...","Check-in: After 4:00 pm,Check out: 11:00 am,Se...",9909,Japan,1,2,5,0,1,0,16,11.0

In [30]:
df.to_csv('Cleaned_Data.csv')